import { Layout } from "components/layout";
import Link from "next/link";

export default function IndexPage() {

    return (
        <Layout>
            <ul>
                <li>
                    <Link href="/static">Go to Static Page</Link>
                    <p>The page is generated by NextJS on server side and is static.</p>
                </li>
                <li>
                    <Link href="/dynamic">Go to Dynamic Page</Link>
                    <p>On Dynamic page, the list of entries is dynamically requested by the client and we can integrate filtering for instance.</p>
                </li>
            </ul>
        </Layout>
    )
}